services:
  mongodb:
    build:
      context: ./Docker
      dockerfile: Dockerfile.mongo
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      MONGO_COMMAND: "mongosh"
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
