services:
  api:
    build:
      context: .
      dockerfile: Docker/Dockerfile.app
    command: ["node", "dist/index.js"]
    depends_on:
      - database
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DATABASE_URL=mongodb://database:27017/fms?authSource=admin&directConnection=true
  # analytics process
  rollups:
    build:
      context: .
      dockerfile: Docker/Dockerfile.scripts
    command: ["node", "dist/src/modules/analytics/analytics.rollup.js"]
    depends_on:
      - database
    restart: unless-stopped
    environment:
      - DATABASE_URL=mongodb://database:27017/fms?authSource=admin&directConnection=true
  iot:
    build:
      context: .
      dockerfile: Docker/Dockerfile.scripts
    command: ["node", "dist/src/simulation/sendSensorData.js"]
    depends_on:
      - database
    restart: unless-stopped
    environment:
      - DATABASE_URL=mongodb://database:27017/fms?authSource=admin&directConnection=true
  database:
    build:
      context: ./Docker
      dockerfile: Dockerfile.mongo
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      MONGO_COMMAND: "mongosh"
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
