services:
  web:
    build:
      context: .
      dockerfile: Docker/Dockerfile.web
    command: echo "Frontend built" # Only builds and exits
    volumes:
      - web-dist:/export

  api:
    build:
      context: .
      dockerfile: Docker/Dockerfile.api
    depends_on:
      - mongodb
      - web
    ports:
      - "3003:3003"
    environment:
      - PORT=3003
      - DATABASE_URL=mongodb://mongodb:27017/fms?authSource=admin
    volumes:
      - web-dist:/export

  mongodb:
    build:
      context: ./Docker
      dockerfile: Dockerfile.mongo
      args:
        MONGO_VERSION: 6
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27017
      MONGO_COMMAND: "mongosh"
    ports:
      - "27017:27017"
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db

volumes:
  web-dist:
  mongo-data:
