FROM node:20-alpine

WORKDIR /app

# Install deps with npm only
COPY FMS_API/package.json FMS_API/package-lock.json ./
RUN npm install

# Copy app source
COPY FMS_API ./

# Build TypeScript
RUN npm run build

EXPOSE 3000

# Run compiled JS
CMD ["node", "dist/index.js"]
