# Build frontend
FROM node:20-slim AS builder

WORKDIR /app

COPY FMS_WEB/package.json FMS_WEB/pnpm-lock.yaml ./
RUN npm install -g pnpm
RUN pnpm install

COPY FMS_WEB ./
RUN pnpm build

# Step 2: Copy dist to a shared folder for API (we server it in express later)
FROM debian:bullseye-slim
WORKDIR /export
COPY --from=builder /app/dist ./dist